version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: autos_db
      POSTGRES_USER: autos_user
      POSTGRES_PASSWORD: autos_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autos_user -d autos_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./autos/backend
      dockerfile: Dockerfile
    volumes:
      - ./autos/backend:/app
    environment:
      - DATABASE_URL=postgresql://autos_user:autos_pass@db:5432/autos_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: bash -c "sleep 5 && python -m app.wait_for_db && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./autos/frontend
      dockerfile: Dockerfile
    volumes:
      - ./autos/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_data:
